// actions
export const OPEN_EXCHANGE = "OPEN_EXCHANGE";
export const CLOSE_EXCHANGE = "CLOSE_EXCHANGE";
export const REQUEST_EXCHANGE_STATUS = "REQUEST_EXCHANGE_STATUS";
export const RECEIVE_EXCHANGE_STATUS = "RECEIVE_EXCHANGE_STATUS";
export const REQUEST_EXCHANGE_DATA = "REQUEST_EXCHANGE_DATA";
export const RECEIVE_EXCHANGE_DATA = "RECEIVE_EXCHANGE_DATA";
export const ADD_CLIENT = "ADD_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const REQUEST_CLIENTS_DATA = "REQUEST_CLIENTS_DATA";
export const RECEIVE_CLIENTS_DATA = "RECEIVE_CLIENTS_DATA";

// misc
export const IS_EXCHANGE_OPEN = 'IS_EXCHANGE_OPEN'
export const EXCHANGE_INFO = 'EXCHANGE_INFO'